service: serverless-typescript-monorepo-debug-example

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: src/handler.hello
    events:
      - http:
          path: /
          method: get

plugins:
  - serverless-webpack
  - serverless-offline
