service: serverless-typescript-monorepo-debug-example

provider:
  name: aws
  runtime: nodejs12.x

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: /
          method: get

plugins:
  - serverless-webpack
  - serverless-offline
